    //更多产品模块的js-----------------------
    $("#more_product").mouseenter(function(){
        $("#more_product").css('display','none');
        $("#nav_div").css('display','block');
    });
    $("#nav_div").mouseleave(function(){
        $("#more_product").css('display','inline-block');
        $("#nav_div").css('display','none');
    });
     //导航、新闻、音乐、购物、视频模块的js-----------------------
    $("#s_menus_1").click(function(){
        $(".s-menu.current").removeClass("current");
        $("#s_menus_1").addClass("current");
        $(".s-content.s-current").removeClass("s-current");
        $("#s_content_1").addClass("s-current");
        $("#s_content_1").css('display','block');
        $("#s_content_2,#s_content_3,#s_content_4,#s_content_5").css('display','none');
    });
    $("#s_menus_2").click(function(){
        $(".s-menu.current").removeClass("current");
        $("#s_menus_2").addClass("current");
        $(".s-content.s-current").removeClass("s-current");
        $("#s_content_2").addClass("s-current");
        $("#s_content_2").css('display','block');
        $("#s_content_1,#s_content_3,#s_content_4,#s_content_5").css('display','none');
    });
    $("#s_menus_3").click(function(){
        $(".s-menu.current").removeClass("current");
        $("#s_menus_3").addClass("current");
        $(".s-content.s-current").removeClass("s-current");
        $("#s_content_3").addClass("s-current");
        $("#s_content_3").css('display','block');
        $("#s_content_1,#s_content_2,#s_content_4,#s_content_5").css('display','none');
    });
    $("#s_menus_4").click(function(){
        $(".s-menu.current").removeClass("current");
        $("#s_menus_4").addClass("current");
        $(".s-content.s-current").removeClass("s-current");
        $("#s_content_4").addClass("s-current");
        $("#s_content_4").css('display','block');
        $("#s_content_1,#s_content_2,#s_content_3,#s_content_5").css('display','none');
    });
    $("#s_menus_5").click(function(){
        $(".s-menu.current").removeClass("current");
        $("#s_menus_5").addClass("current");
        $(".s-content.s-current").removeClass("s-current");
        $("#s_content_5").addClass("s-current");
        $("#s_content_5").css('display','block');
        $("#s_content_1,#s_content_2,#s_content_3,#s_content_4").css('display','none');
    });
    // 我的导航和推荐导航的js
    $("#tab_nav").click(function(){
        $("#s_nav").css('display','block');
        $("#s_nused").css('display','none'); 
        $(".tab-common.tab-on").removeClass("tab-on");
        $("#tab_nav").addClass("tab-on");
    });
    $("#tab_used").click(function(){
        $("#s_nused").css('display','block');
        $("#s_nav").css('display','none'); 
        $(".tab-common.tab-on").removeClass("tab-on");
        $("#tab_used").addClass("tab-on");
    });
 